unit_tests_with_coverage:
  # A job is always executed within a stage.
  # If no stage is set, it defaults to 'test'.
  stage: test
  
  # Here you can execute arbitrate terminal commands.
  # If any of the commands returns a non zero exit code the job fails.
  script:
    - mvn test
    